/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.loginb;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import static junit.runner.Version.id;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;



/**
 *
 * @author adanel
 */
public class ConsultarCursos extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarCursos
     */
    public ConsultarCursos() {
        initComponents();
        Actualizar();
        
    }
    public void Actualizar() {
         this.setLocationRelativeTo(null);
        DefaultTableModel data = new DefaultTableModel(new String[]{"ID","nombre","seccion","fechaInicio","fechaFin","horaInicio","horaFin","profeso"},Loginb.cursos.size());
        jTable1.setModel(data);
        
        int row = 0;
        
        for(Curso g : Loginb.cursos ){
            jTable1.setValueAt(g.ID, row, 0);
            jTable1.setValueAt(g.nombre, row, 1);
            jTable1.setValueAt(g.seccion, row, 2);
            jTable1.setValueAt(g.fechaInicio, row, 3);
            jTable1.setValueAt(g.fechaFin, row, 4);
            jTable1.setValueAt(g.horaInicio, row, 5);
            jTable1.setValueAt(g.horaFin, row, 6);
            jTable1.setValueAt(g.profesor, row, 7);

            row ++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Editar Curso");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cargar Archivo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        EditarCurso m = new EditarCurso(jTable1.getSelectedRow());
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFileChooser chooser = new JFileChooser();
    int returnVal = chooser.showOpenDialog(this);
    if(returnVal == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();
        leer(file.getAbsolutePath());
        
    }
        
    
        
    }//GEN-LAST:event_jButton3ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

   
  public  void leer(String rutaConNombre){
       
         try{
           FileReader r = new FileReader(rutaConNombre);
            JSONParser jp = new JSONParser();
            Object obj = jp.parse(r);
            JSONArray cursosList = (JSONArray) obj;
            for(Object c:cursosList){
                 JSONObject curso = (JSONObject) c;
              
               long ID = (long) curso.get("id");
                int IDEntero = (int) ID;
                String nombre = (String) curso.get("nombre");
                String seccion = (String) curso.get("seccion");
                String fechaInicio = (String) curso.get("fecha_inicio");
                String fechaFin = (String) curso.get("fecha_fin");
                String horaInicio = (String) curso.get("hora_inicio");
                String horaFin = (String) curso.get("hora_fin");
                String profesor = (String) curso.get("profesor");
                
                    Curso nuevoCurso = new Curso();
                    nuevoCurso.ID = (int)ID;
                    nuevoCurso.nombre = nombre;
                    nuevoCurso.seccion = seccion;
                    nuevoCurso.fechaInicio = fechaInicio ;
                    nuevoCurso.fechaFin = fechaFin;
                    nuevoCurso.horaInicio = horaInicio;
                    nuevoCurso.horaFin = horaFin;
                    nuevoCurso.profesor = profesor;

                    Loginb.cursos.add(nuevoCurso);
             
               
                }Actualizar();
                
                
            }catch(Exception e){
            e.printStackTrace();
            
        }
        }
        
    }
    

